### ISSUE TITLE
Conflict with RoadRunner - 1.16.5

### ISSUE THREAD

**Issue by Aarods** [MCTeamPotato/Redirectionor#1]
When trying to start a server it crashes on initial load, it seems to have conflicts with Roadrunner, in the latest version of both mods. Here I show an image that comes out before the server crashes.
![image](https://github.com/MCTeamPotato/Redirectionor/assets/110215990/98b37eae-6f47-4b3e-a2da-bf5ea1184880)

I'm not sure if it's another mod, but in testing mods of yours like Goal Optimizer and this one, they conflict with Roadrunner.

**Comment by Kasualix** [comment]
I will ensure roadrunner compatibility in the next version but I just don't recommend using it because it is heavily out dated and has a lot of tiny incompatibility problems with other content mods. (Actually, when I removed it from my performance pack, my max fps went up to 500 from 300. This is only my own situation and maybe for others it's not bad, though)

**Comment by Kasualix** [comment]
Can you provide the full log?

**Comment by Aarods** [comment]
Sure, here it is.
[latest.log](https://github.com/MCTeamPotato/Redirectionor/files/11850208/latest.log)

**Comment by Kasualix** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/redirectionor/files/4607078
Just released, this version is fully compatible with roadrunner.
For Goal Optimizer, you can temporarily abandon it if you are stick to roadrunner because I'm currently working on Alex's Mobs integration for it (This is a lot of work), after which I will make it compatible with roadrunner.

**Comment by Kasualix** [comment]
Goal Optimizer is compatible with roadrunner too.

**Comment by Aarods** [comment]
![image](https://github.com/MCTeamPotato/Redirectionor/assets/110215990/a77f85e9-e335-4797-8994-8ec7485cd871)
Starting on server there is another error or the same one (I'm not sure) and for client it keeps freezing on the loading screen.

Server log (With Roadrunner):
[latest (1).log](https://github.com/MCTeamPotato/Redirectionor/files/11858029/latest.1.log)

Client log: (Without Roadrunner):
[latest.log](https://github.com/MCTeamPotato/Redirectionor/files/11858037/latest.log)

**Comment by Kasualix** [comment]
How about 1.0.1? https://legacy.curseforge.com/minecraft/mc-mods/redirectionor/files/4607693

**Comment by Aarods** [comment]
In the Client Side it works, but in the server side it still crashes.
[latest.log](https://github.com/MCTeamPotato/Redirectionor/files/11858125/latest.log)

**Comment by Kasualix** [comment]
should be fully fixed in 1.1.0, thanks to your report!
